version: '3.4'

services:
  dotnetcoreasysnsample-angular-client:    
    build:
      context: ./client
      dockerfile: angular.release.dockerfile
    ports:
      - "80:80"
    depends_on: 
      - dotnetcoreasysnsample-api

  dotnetcoreasysnsample-api:    
    build:
      context: ./server/DotNetCoreAsysnSample
      dockerfile: aspnetcore.release.dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SEQ_URL=http://dotnetcoreasysnsample-seq:5341
    depends_on: 
      - dotnetcoreasysnsample-db
      - dotnetcoreasysnsample-seq
  
  dotnetcoreasysnsample-db:
    build:
        context: .
        dockerfile: sql/sql.Dockerfile
    restart: always
    ports:
        - "1433:1433"   
    environment:      
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Sqlc0ntainersFTW!
        - MSSQL_PID=Express 
  
  dotnetcoreasysnsample-seq:    
    image: datalust/seq    
    ports:
        - '8005:80'      
    environment:
        - ACCEPT_EULA=Y 